// Code generated by "stringer -type=CursorType"; DO NOT EDIT

package stream

import "fmt"

const _CursorType_name = "WriteCursorReadForwardCursorReadBidirectionalCursor"

var _CursorType_index = [...]uint8{0, 11, 28, 51}

func (i CursorType) String() string {
	if i < 0 || i >= CursorType(len(_CursorType_index)-1) {
		return fmt.Sprintf("CursorType(%d)", i)
	}
	return _CursorType_name[_CursorType_index[i]:_CursorType_index[i+1]]
}
