// Code generated by "stringer -type=StreamEntryType"; DO NOT EDIT

package stream

import "fmt"

const _StreamEntryType_name = "StreamEntrySnapshotStreamEntryMutation"

var _StreamEntryType_index = [...]uint8{0, 19, 38}

func (i StreamEntryType) String() string {
	if i < 0 || i >= StreamEntryType(len(_StreamEntryType_index)-1) {
		return fmt.Sprintf("StreamEntryType(%d)", i)
	}
	return _StreamEntryType_name[_StreamEntryType_index[i]:_StreamEntryType_index[i+1]]
}
